from openai import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    RateLimitError,
)

from connection import GROQ_MODEL, create_groq_client
from prompt import create_error_prompt


def explain_error(error_log):
    """
    Analyze an error log using Groq and return a simple Hindi explanation.

    Args:
        error_log (str): Error message, log, exception, or stack trace.

    Returns:
        str: Structured error explanation generated by the AI.

    Raises:
        ValueError: If the input or AI response is empty.
        RuntimeError: If the Groq API request fails.
    """

    # This function comes from prompt.py.
    # It also validates blank and invalid input.
    final_prompt = create_error_prompt(error_log)

    client = create_groq_client()

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are ErrorSamjho AI, a technical error "
                        "analysis assistant. Follow the user's requested "
                        "output format accurately."
                    ),
                },
                {
                    "role": "user",
                    "content": final_prompt,
                },
            ],
            temperature=0.2,
            max_tokens=1500,
        )

        if not response.choices:
            raise ValueError(
                "The AI returned an empty response."
            )

        message = response.choices[0].message

        if message is None or not message.content:
            raise ValueError(
                "The AI response did not contain an explanation."
            )

        return message.content.strip()

    except AuthenticationError as error:
        raise RuntimeError(
            "Groq authentication failed. Check GROQ_API_KEY "
            "inside the .env file."
        ) from error

    except RateLimitError as error:
        raise RuntimeError(
            "Groq API rate limit or usage limit exceeded. "
            "Please wait and try again."
        ) from error

    except APITimeoutError as error:
        raise RuntimeError(
            "Groq API request timed out. Check your internet "
            "connection and try again."
        ) from error

    except APIConnectionError as error:
        raise RuntimeError(
            "Unable to connect to Groq API. Check your internet, "
            "VPN, proxy, firewall, or SSL certificate configuration."
        ) from error

    except BadRequestError as error:
        raise RuntimeError(
            "Groq rejected the request. Check the configured model "
            "name and API request."
        ) from error

    except APIError as error:
        raise RuntimeError(
            f"Groq API returned an error: {error}"
        ) from error