import time
from collections import deque
from threading import Lock

from openai import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    RateLimitError,
)

from connection import (
    GROQ_MODEL,
    MAX_ERROR_LOG_LENGTH,
    MIN_ERROR_LOG_LENGTH,
    create_groq_client,
)
from prompt import create_error_prompt


class RateLimiter:
    """Simple in-memory rate limiter for API calls."""

    def __init__(self, max_calls=3, window_seconds=60):
        if not isinstance(max_calls, int) or max_calls <= 0:
            raise ValueError("max_calls must be a positive integer.")
        if not isinstance(window_seconds, (int, float)) or window_seconds <= 0:
            raise ValueError("window_seconds must be positive.")

        self.max_calls = max_calls
        self.window_seconds = window_seconds
        self._timestamps = deque()
        self._lock = Lock()

    def acquire(self):
        with self._lock:
            now = time.monotonic()
            window_start = now - self.window_seconds

            while self._timestamps and self._timestamps[0] <= window_start:
                self._timestamps.popleft()

            if len(self._timestamps) >= self.max_calls:
                wait_time = max(
                    1,
                    int(self.window_seconds - (now - self._timestamps[0])) + 1,
                )
                raise RuntimeError(
                    "Rate limit reached. Please wait "
                    f"about {wait_time} seconds before trying again."
                )

            self._timestamps.append(now)
            return True

    @property
    def remaining(self):
        with self._lock:
            now = time.monotonic()
            window_start = now - self.window_seconds

            while self._timestamps and self._timestamps[0] <= window_start:
                self._timestamps.popleft()

            return max(self.max_calls - len(self._timestamps), 0)


def validate_error_log(error_log, min_chars=MIN_ERROR_LOG_LENGTH, max_chars=MAX_ERROR_LOG_LENGTH):
    """Validate the user input before making an API call."""
    if not isinstance(error_log, str):
        raise TypeError("Error log must be provided as text.")

    cleaned_error_log = error_log.strip()

    if not cleaned_error_log:
        raise ValueError("Error log cannot be empty.")

    if len(cleaned_error_log) < min_chars:
        raise ValueError(
            f"Error log is too short. Please provide at least {min_chars} characters."
        )

    if len(cleaned_error_log) > max_chars:
        raise ValueError(
            f"Error log is too long. Please keep it under {max_chars} characters."
        )

    return cleaned_error_log


def explain_error(error_log, rate_limiter=None):
    """
    Analyze an error log using Groq and return a simple Hindi explanation.

    Args:
        error_log (str): Error message, log, exception, or stack trace.
        rate_limiter (RateLimiter | None): Optional API rate limiter.

    Returns:
        str: Structured error explanation generated by the AI.

    Raises:
        ValueError: If the input or AI response is empty.
        RuntimeError: If the Groq API request fails.
    """
    cleaned_error_log = validate_error_log(error_log)

    if rate_limiter is not None:
        rate_limiter.acquire()

    final_prompt = create_error_prompt(cleaned_error_log)

    client = create_groq_client()

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are ErrorSamjho AI, a technical error "
                        "analysis assistant. Follow the user's requested "
                        "output format accurately."
                    ),
                },
                {
                    "role": "user",
                    "content": final_prompt,
                },
            ],
            temperature=0.2,
            max_tokens=1500,
        )

        if not response.choices:
            raise ValueError("The AI returned an empty response.")

        message = response.choices[0].message

        if message is None or not isinstance(message.content, str):
            raise ValueError(
                "The AI response did not contain an explanation."
            )

        cleaned_response = message.content.strip()
        if not cleaned_response:
            raise ValueError("The AI response did not contain an explanation.")

        return cleaned_response

    except AuthenticationError as error:
        raise RuntimeError(
            "Groq authentication failed. Check GROQ_API_KEY "
            "inside the .env file."
        ) from error

    except RateLimitError as error:
        raise RuntimeError(
            "Groq API rate limit or usage limit exceeded. "
            "Please wait and try again."
        ) from error

    except APITimeoutError as error:
        raise RuntimeError(
            "Groq API request timed out. Check your internet "
            "connection and try again."
        ) from error

    except APIConnectionError as error:
        raise RuntimeError(
            "Unable to connect to Groq API. Check your internet, "
            "VPN, proxy, firewall, or SSL certificate configuration."
        ) from error

    except BadRequestError as error:
        raise RuntimeError(
            "Groq rejected the request. Check the configured model "
            "name and API request."
        ) from error

    except APIError as error:
        raise RuntimeError(
            f"Groq API returned an error: {error}"
        ) from error